fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  logoText
  logoImage
  navLinks {
    __typename
    label
    href
  }
  navCtaLabel
  navCtaLink
  footerTagline
  footerLinks {
    __typename
    label
    href
  }
  copyrightText
  googleFontsUrl
  socialLinks {
    __typename
    platform
    url
  }
}

fragment HomeParts on Home {
  __typename
  title
  eyebrow
  headline
  description
  primaryCtaLabel
  primaryCtaLink
  secondaryCtaLabel
  secondaryCtaLink
  sectionHeading
  sectionBody
}

fragment AboutParts on About {
  __typename
  title
  eyebrow
  headline
  description
  sectionHeading
  sectionBody
}

fragment ServicesParts on Services {
  __typename
  title
  eyebrow
  headline
  description
  items {
    __typename
    title
    description
  }
  ctaLabel
  ctaLink
}

fragment ContactParts on Contact {
  __typename
  title
  eyebrow
  headline
  description
  email
  phone
  address
  ctaLabel
  ctaLink
}
