fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  logoText
  logoImage
  navLinks {
    __typename
    label
    href
  }
  navCtaLabel
  navCtaLink
  footerTagline
  footerLinks {
    __typename
    label
    href
  }
  copyrightText
  googleFontsUrl
  socialLinks {
    __typename
    platform
    url
  }
}

fragment HomeParts on Home {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  heroImage
  heroImageAlt
  primaryCtaLabel
  primaryCtaLink
  secondaryCtaLabel
  secondaryCtaLink
  heroStats {
    __typename
    value
    label
  }
  capabilityEyebrow
  capabilityHeadline
  capabilities {
    __typename
    title
    description
    spec
  }
  qualityEyebrow
  qualityHeadline
  qualityDescription
  qualityPoints {
    __typename
    label
    value
  }
  proofEyebrow
  proofHeadline
  testimonials {
    __typename
    quote
    author
    role
  }
  proofCtaLabel
  proofCtaLink
}

fragment AboutParts on About {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  timelineEyebrow
  timelineHeadline
  milestones {
    __typename
    year
    title
    description
  }
  certificationsEyebrow
  certificationsHeadline
  certifications {
    __typename
    name
    details
  }
  footprintEyebrow
  footprintHeadline
  footprintDescription
  footprintStats {
    __typename
    value
    label
  }
  ctaLabel
  ctaLink
}

fragment ServicesParts on Services {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  serviceCards {
    __typename
    name
    description
    tolerance
    materials
  }
  processEyebrow
  processHeadline
  processSteps {
    __typename
    step
    title
    description
  }
  ctaHeading
  ctaDescription
  ctaLabel
  ctaLink
}

fragment ContactParts on Contact {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  formHeading
  formDescription
  uploadHint
  emailLabel
  emailValue
  phoneLabel
  phoneValue
  addressLabel
  addressValue
  hoursLabel
  hoursValue
  responseLabel
  responseValue
  testimonialQuote
  testimonialAuthor
  ctaLabel
  ctaLink
}
