//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  settings: Settings;
  settingsConnection: SettingsConnection;
  home: Home;
  homeConnection: HomeConnection;
  about: About;
  aboutConnection: AboutConnection;
  services: Services;
  servicesConnection: ServicesConnection;
  contact: Contact;
  contactConnection: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryServicesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};

export type DocumentFilter = {
  settings?: InputMaybe<SettingsFilter>;
  home?: InputMaybe<HomeFilter>;
  about?: InputMaybe<AboutFilter>;
  services?: InputMaybe<ServicesFilter>;
  contact?: InputMaybe<ContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Settings | Home | About | Services | Contact | Folder;

export type SettingsNavLinks = {
  __typename?: 'SettingsNavLinks';
  label: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type SettingsFooterLinks = {
  __typename?: 'SettingsFooterLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type SettingsSocialLinks = {
  __typename?: 'SettingsSocialLinks';
  platform?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  siteName: Scalars['String']['output'];
  siteTagline?: Maybe<Scalars['String']['output']>;
  logoText?: Maybe<Scalars['String']['output']>;
  logoImage?: Maybe<Scalars['String']['output']>;
  navLinks?: Maybe<Array<Maybe<SettingsNavLinks>>>;
  navCtaLabel?: Maybe<Scalars['String']['output']>;
  navCtaLink?: Maybe<Scalars['String']['output']>;
  footerTagline?: Maybe<Scalars['String']['output']>;
  footerLinks?: Maybe<Array<Maybe<SettingsFooterLinks>>>;
  copyrightText?: Maybe<Scalars['String']['output']>;
  googleFontsUrl?: Maybe<Scalars['String']['output']>;
  socialLinks?: Maybe<Array<Maybe<SettingsSocialLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsNavLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SettingsFooterLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SettingsSocialLinksFilter = {
  platform?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  siteTagline?: InputMaybe<StringFilter>;
  logoText?: InputMaybe<StringFilter>;
  logoImage?: InputMaybe<ImageFilter>;
  navLinks?: InputMaybe<SettingsNavLinksFilter>;
  navCtaLabel?: InputMaybe<StringFilter>;
  navCtaLink?: InputMaybe<StringFilter>;
  footerTagline?: InputMaybe<StringFilter>;
  footerLinks?: InputMaybe<SettingsFooterLinksFilter>;
  copyrightText?: InputMaybe<StringFilter>;
  googleFontsUrl?: InputMaybe<StringFilter>;
  socialLinks?: InputMaybe<SettingsSocialLinksFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type HomeHeroStats = {
  __typename?: 'HomeHeroStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type HomeCapabilities = {
  __typename?: 'HomeCapabilities';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  spec?: Maybe<Scalars['String']['output']>;
};

export type HomeQualityPoints = {
  __typename?: 'HomeQualityPoints';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type HomeTestimonials = {
  __typename?: 'HomeTestimonials';
  quote?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  title: Scalars['String']['output'];
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroHeadline: Scalars['String']['output'];
  heroDescription?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  heroImageAlt?: Maybe<Scalars['String']['output']>;
  primaryCtaLabel?: Maybe<Scalars['String']['output']>;
  primaryCtaLink?: Maybe<Scalars['String']['output']>;
  secondaryCtaLabel?: Maybe<Scalars['String']['output']>;
  secondaryCtaLink?: Maybe<Scalars['String']['output']>;
  heroStats?: Maybe<Array<Maybe<HomeHeroStats>>>;
  capabilityEyebrow?: Maybe<Scalars['String']['output']>;
  capabilityHeadline?: Maybe<Scalars['String']['output']>;
  capabilities?: Maybe<Array<Maybe<HomeCapabilities>>>;
  qualityEyebrow?: Maybe<Scalars['String']['output']>;
  qualityHeadline?: Maybe<Scalars['String']['output']>;
  qualityDescription?: Maybe<Scalars['String']['output']>;
  qualityPoints?: Maybe<Array<Maybe<HomeQualityPoints>>>;
  proofEyebrow?: Maybe<Scalars['String']['output']>;
  proofHeadline?: Maybe<Scalars['String']['output']>;
  testimonials?: Maybe<Array<Maybe<HomeTestimonials>>>;
  proofCtaLabel?: Maybe<Scalars['String']['output']>;
  proofCtaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomeHeroStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HomeCapabilitiesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  spec?: InputMaybe<StringFilter>;
};

export type HomeQualityPointsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type HomeTestimonialsFilter = {
  quote?: InputMaybe<StringFilter>;
  author?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  title?: InputMaybe<StringFilter>;
  heroEyebrow?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  heroImageAlt?: InputMaybe<StringFilter>;
  primaryCtaLabel?: InputMaybe<StringFilter>;
  primaryCtaLink?: InputMaybe<StringFilter>;
  secondaryCtaLabel?: InputMaybe<StringFilter>;
  secondaryCtaLink?: InputMaybe<StringFilter>;
  heroStats?: InputMaybe<HomeHeroStatsFilter>;
  capabilityEyebrow?: InputMaybe<StringFilter>;
  capabilityHeadline?: InputMaybe<StringFilter>;
  capabilities?: InputMaybe<HomeCapabilitiesFilter>;
  qualityEyebrow?: InputMaybe<StringFilter>;
  qualityHeadline?: InputMaybe<StringFilter>;
  qualityDescription?: InputMaybe<StringFilter>;
  qualityPoints?: InputMaybe<HomeQualityPointsFilter>;
  proofEyebrow?: InputMaybe<StringFilter>;
  proofHeadline?: InputMaybe<StringFilter>;
  testimonials?: InputMaybe<HomeTestimonialsFilter>;
  proofCtaLabel?: InputMaybe<StringFilter>;
  proofCtaLink?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type AboutMilestones = {
  __typename?: 'AboutMilestones';
  year?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutCertifications = {
  __typename?: 'AboutCertifications';
  name?: Maybe<Scalars['String']['output']>;
  details?: Maybe<Scalars['String']['output']>;
};

export type AboutFootprintStats = {
  __typename?: 'AboutFootprintStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  title: Scalars['String']['output'];
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroHeadline: Scalars['String']['output'];
  heroDescription?: Maybe<Scalars['String']['output']>;
  timelineEyebrow?: Maybe<Scalars['String']['output']>;
  timelineHeadline?: Maybe<Scalars['String']['output']>;
  milestones?: Maybe<Array<Maybe<AboutMilestones>>>;
  certificationsEyebrow?: Maybe<Scalars['String']['output']>;
  certificationsHeadline?: Maybe<Scalars['String']['output']>;
  certifications?: Maybe<Array<Maybe<AboutCertifications>>>;
  footprintEyebrow?: Maybe<Scalars['String']['output']>;
  footprintHeadline?: Maybe<Scalars['String']['output']>;
  footprintDescription?: Maybe<Scalars['String']['output']>;
  footprintStats?: Maybe<Array<Maybe<AboutFootprintStats>>>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutMilestonesFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutCertificationsFilter = {
  name?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
};

export type AboutFootprintStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  title?: InputMaybe<StringFilter>;
  heroEyebrow?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  timelineEyebrow?: InputMaybe<StringFilter>;
  timelineHeadline?: InputMaybe<StringFilter>;
  milestones?: InputMaybe<AboutMilestonesFilter>;
  certificationsEyebrow?: InputMaybe<StringFilter>;
  certificationsHeadline?: InputMaybe<StringFilter>;
  certifications?: InputMaybe<AboutCertificationsFilter>;
  footprintEyebrow?: InputMaybe<StringFilter>;
  footprintHeadline?: InputMaybe<StringFilter>;
  footprintDescription?: InputMaybe<StringFilter>;
  footprintStats?: InputMaybe<AboutFootprintStatsFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ServicesServiceCards = {
  __typename?: 'ServicesServiceCards';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  tolerance?: Maybe<Scalars['String']['output']>;
  materials?: Maybe<Scalars['String']['output']>;
};

export type ServicesProcessSteps = {
  __typename?: 'ServicesProcessSteps';
  step?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Services = Node & Document & {
  __typename?: 'Services';
  title: Scalars['String']['output'];
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroHeadline: Scalars['String']['output'];
  heroDescription?: Maybe<Scalars['String']['output']>;
  serviceCards?: Maybe<Array<Maybe<ServicesServiceCards>>>;
  processEyebrow?: Maybe<Scalars['String']['output']>;
  processHeadline?: Maybe<Scalars['String']['output']>;
  processSteps?: Maybe<Array<Maybe<ServicesProcessSteps>>>;
  ctaHeading?: Maybe<Scalars['String']['output']>;
  ctaDescription?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesServiceCardsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tolerance?: InputMaybe<StringFilter>;
  materials?: InputMaybe<StringFilter>;
};

export type ServicesProcessStepsFilter = {
  step?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ServicesFilter = {
  title?: InputMaybe<StringFilter>;
  heroEyebrow?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  serviceCards?: InputMaybe<ServicesServiceCardsFilter>;
  processEyebrow?: InputMaybe<StringFilter>;
  processHeadline?: InputMaybe<StringFilter>;
  processSteps?: InputMaybe<ServicesProcessStepsFilter>;
  ctaHeading?: InputMaybe<StringFilter>;
  ctaDescription?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type ServicesConnectionEdges = {
  __typename?: 'ServicesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Services>;
};

export type ServicesConnection = Connection & {
  __typename?: 'ServicesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  title: Scalars['String']['output'];
  heroEyebrow?: Maybe<Scalars['String']['output']>;
  heroHeadline: Scalars['String']['output'];
  heroDescription?: Maybe<Scalars['String']['output']>;
  formHeading?: Maybe<Scalars['String']['output']>;
  formDescription?: Maybe<Scalars['String']['output']>;
  uploadHint?: Maybe<Scalars['String']['output']>;
  emailLabel?: Maybe<Scalars['String']['output']>;
  emailValue?: Maybe<Scalars['String']['output']>;
  phoneLabel?: Maybe<Scalars['String']['output']>;
  phoneValue?: Maybe<Scalars['String']['output']>;
  addressLabel?: Maybe<Scalars['String']['output']>;
  addressValue?: Maybe<Scalars['String']['output']>;
  hoursLabel?: Maybe<Scalars['String']['output']>;
  hoursValue?: Maybe<Scalars['String']['output']>;
  responseLabel?: Maybe<Scalars['String']['output']>;
  responseValue?: Maybe<Scalars['String']['output']>;
  testimonialQuote?: Maybe<Scalars['String']['output']>;
  testimonialAuthor?: Maybe<Scalars['String']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  title?: InputMaybe<StringFilter>;
  heroEyebrow?: InputMaybe<StringFilter>;
  heroHeadline?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  formHeading?: InputMaybe<StringFilter>;
  formDescription?: InputMaybe<StringFilter>;
  uploadHint?: InputMaybe<StringFilter>;
  emailLabel?: InputMaybe<StringFilter>;
  emailValue?: InputMaybe<StringFilter>;
  phoneLabel?: InputMaybe<StringFilter>;
  phoneValue?: InputMaybe<StringFilter>;
  addressLabel?: InputMaybe<StringFilter>;
  addressValue?: InputMaybe<StringFilter>;
  hoursLabel?: InputMaybe<StringFilter>;
  hoursValue?: InputMaybe<StringFilter>;
  responseLabel?: InputMaybe<StringFilter>;
  responseValue?: InputMaybe<StringFilter>;
  testimonialQuote?: InputMaybe<StringFilter>;
  testimonialAuthor?: InputMaybe<StringFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSettings: Settings;
  createSettings: Settings;
  updateHome: Home;
  createHome: Home;
  updateAbout: About;
  createAbout: About;
  updateServices: Services;
  createServices: Services;
  updateContact: Contact;
  createContact: Contact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationCreateServicesArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};

export type DocumentUpdateMutation = {
  settings?: InputMaybe<SettingsMutation>;
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  settings?: InputMaybe<SettingsMutation>;
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  services?: InputMaybe<ServicesMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type SettingsNavLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsFooterLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsSocialLinksMutation = {
  platform?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  siteTagline?: InputMaybe<Scalars['String']['input']>;
  logoText?: InputMaybe<Scalars['String']['input']>;
  logoImage?: InputMaybe<Scalars['String']['input']>;
  navLinks?: InputMaybe<Array<InputMaybe<SettingsNavLinksMutation>>>;
  navCtaLabel?: InputMaybe<Scalars['String']['input']>;
  navCtaLink?: InputMaybe<Scalars['String']['input']>;
  footerTagline?: InputMaybe<Scalars['String']['input']>;
  footerLinks?: InputMaybe<Array<InputMaybe<SettingsFooterLinksMutation>>>;
  copyrightText?: InputMaybe<Scalars['String']['input']>;
  googleFontsUrl?: InputMaybe<Scalars['String']['input']>;
  socialLinks?: InputMaybe<Array<InputMaybe<SettingsSocialLinksMutation>>>;
};

export type HomeHeroStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HomeCapabilitiesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  spec?: InputMaybe<Scalars['String']['input']>;
};

export type HomeQualityPointsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type HomeTestimonialsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  heroImageAlt?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  primaryCtaLink?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaLabel?: InputMaybe<Scalars['String']['input']>;
  secondaryCtaLink?: InputMaybe<Scalars['String']['input']>;
  heroStats?: InputMaybe<Array<InputMaybe<HomeHeroStatsMutation>>>;
  capabilityEyebrow?: InputMaybe<Scalars['String']['input']>;
  capabilityHeadline?: InputMaybe<Scalars['String']['input']>;
  capabilities?: InputMaybe<Array<InputMaybe<HomeCapabilitiesMutation>>>;
  qualityEyebrow?: InputMaybe<Scalars['String']['input']>;
  qualityHeadline?: InputMaybe<Scalars['String']['input']>;
  qualityDescription?: InputMaybe<Scalars['String']['input']>;
  qualityPoints?: InputMaybe<Array<InputMaybe<HomeQualityPointsMutation>>>;
  proofEyebrow?: InputMaybe<Scalars['String']['input']>;
  proofHeadline?: InputMaybe<Scalars['String']['input']>;
  testimonials?: InputMaybe<Array<InputMaybe<HomeTestimonialsMutation>>>;
  proofCtaLabel?: InputMaybe<Scalars['String']['input']>;
  proofCtaLink?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMilestonesMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutCertificationsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
};

export type AboutFootprintStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  timelineEyebrow?: InputMaybe<Scalars['String']['input']>;
  timelineHeadline?: InputMaybe<Scalars['String']['input']>;
  milestones?: InputMaybe<Array<InputMaybe<AboutMilestonesMutation>>>;
  certificationsEyebrow?: InputMaybe<Scalars['String']['input']>;
  certificationsHeadline?: InputMaybe<Scalars['String']['input']>;
  certifications?: InputMaybe<Array<InputMaybe<AboutCertificationsMutation>>>;
  footprintEyebrow?: InputMaybe<Scalars['String']['input']>;
  footprintHeadline?: InputMaybe<Scalars['String']['input']>;
  footprintDescription?: InputMaybe<Scalars['String']['input']>;
  footprintStats?: InputMaybe<Array<InputMaybe<AboutFootprintStatsMutation>>>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesServiceCardsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tolerance?: InputMaybe<Scalars['String']['input']>;
  materials?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesProcessStepsMutation = {
  step?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ServicesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  serviceCards?: InputMaybe<Array<InputMaybe<ServicesServiceCardsMutation>>>;
  processEyebrow?: InputMaybe<Scalars['String']['input']>;
  processHeadline?: InputMaybe<Scalars['String']['input']>;
  processSteps?: InputMaybe<Array<InputMaybe<ServicesProcessStepsMutation>>>;
  ctaHeading?: InputMaybe<Scalars['String']['input']>;
  ctaDescription?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  heroEyebrow?: InputMaybe<Scalars['String']['input']>;
  heroHeadline?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  formHeading?: InputMaybe<Scalars['String']['input']>;
  formDescription?: InputMaybe<Scalars['String']['input']>;
  uploadHint?: InputMaybe<Scalars['String']['input']>;
  emailLabel?: InputMaybe<Scalars['String']['input']>;
  emailValue?: InputMaybe<Scalars['String']['input']>;
  phoneLabel?: InputMaybe<Scalars['String']['input']>;
  phoneValue?: InputMaybe<Scalars['String']['input']>;
  addressLabel?: InputMaybe<Scalars['String']['input']>;
  addressValue?: InputMaybe<Scalars['String']['input']>;
  hoursLabel?: InputMaybe<Scalars['String']['input']>;
  hoursValue?: InputMaybe<Scalars['String']['input']>;
  responseLabel?: InputMaybe<Scalars['String']['input']>;
  responseValue?: InputMaybe<Scalars['String']['input']>;
  testimonialQuote?: InputMaybe<Scalars['String']['input']>;
  testimonialAuthor?: InputMaybe<Scalars['String']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsPartsFragment = { __typename: 'Settings', siteName: string, siteTagline?: string | null, logoText?: string | null, logoImage?: string | null, navCtaLabel?: string | null, navCtaLink?: string | null, footerTagline?: string | null, copyrightText?: string | null, googleFontsUrl?: string | null, navLinks?: Array<{ __typename: 'SettingsNavLinks', label: string, href: string } | null> | null, footerLinks?: Array<{ __typename: 'SettingsFooterLinks', label?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'SettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null };

export type HomePartsFragment = { __typename: 'Home', title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, heroImage?: string | null, heroImageAlt?: string | null, primaryCtaLabel?: string | null, primaryCtaLink?: string | null, secondaryCtaLabel?: string | null, secondaryCtaLink?: string | null, capabilityEyebrow?: string | null, capabilityHeadline?: string | null, qualityEyebrow?: string | null, qualityHeadline?: string | null, qualityDescription?: string | null, proofEyebrow?: string | null, proofHeadline?: string | null, proofCtaLabel?: string | null, proofCtaLink?: string | null, heroStats?: Array<{ __typename: 'HomeHeroStats', value?: string | null, label?: string | null } | null> | null, capabilities?: Array<{ __typename: 'HomeCapabilities', title?: string | null, description?: string | null, spec?: string | null } | null> | null, qualityPoints?: Array<{ __typename: 'HomeQualityPoints', label?: string | null, value?: string | null } | null> | null, testimonials?: Array<{ __typename: 'HomeTestimonials', quote?: string | null, author?: string | null, role?: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, timelineEyebrow?: string | null, timelineHeadline?: string | null, certificationsEyebrow?: string | null, certificationsHeadline?: string | null, footprintEyebrow?: string | null, footprintHeadline?: string | null, footprintDescription?: string | null, ctaLabel?: string | null, ctaLink?: string | null, milestones?: Array<{ __typename: 'AboutMilestones', year?: string | null, title?: string | null, description?: string | null } | null> | null, certifications?: Array<{ __typename: 'AboutCertifications', name?: string | null, details?: string | null } | null> | null, footprintStats?: Array<{ __typename: 'AboutFootprintStats', value?: string | null, label?: string | null } | null> | null };

export type ServicesPartsFragment = { __typename: 'Services', title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, processEyebrow?: string | null, processHeadline?: string | null, ctaHeading?: string | null, ctaDescription?: string | null, ctaLabel?: string | null, ctaLink?: string | null, serviceCards?: Array<{ __typename: 'ServicesServiceCards', name?: string | null, description?: string | null, tolerance?: string | null, materials?: string | null } | null> | null, processSteps?: Array<{ __typename: 'ServicesProcessSteps', step?: string | null, title?: string | null, description?: string | null } | null> | null };

export type ContactPartsFragment = { __typename: 'Contact', title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, formHeading?: string | null, formDescription?: string | null, uploadHint?: string | null, emailLabel?: string | null, emailValue?: string | null, phoneLabel?: string | null, phoneValue?: string | null, addressLabel?: string | null, addressValue?: string | null, hoursLabel?: string | null, hoursValue?: string | null, responseLabel?: string | null, responseValue?: string | null, testimonialQuote?: string | null, testimonialAuthor?: string | null, ctaLabel?: string | null, ctaLink?: string | null };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, siteName: string, siteTagline?: string | null, logoText?: string | null, logoImage?: string | null, navCtaLabel?: string | null, navCtaLink?: string | null, footerTagline?: string | null, copyrightText?: string | null, googleFontsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks?: Array<{ __typename: 'SettingsNavLinks', label: string, href: string } | null> | null, footerLinks?: Array<{ __typename: 'SettingsFooterLinks', label?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'SettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, siteName: string, siteTagline?: string | null, logoText?: string | null, logoImage?: string | null, navCtaLabel?: string | null, navCtaLink?: string | null, footerTagline?: string | null, copyrightText?: string | null, googleFontsUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navLinks?: Array<{ __typename: 'SettingsNavLinks', label: string, href: string } | null> | null, footerLinks?: Array<{ __typename: 'SettingsFooterLinks', label?: string | null, href?: string | null } | null> | null, socialLinks?: Array<{ __typename: 'SettingsSocialLinks', platform?: string | null, url?: string | null } | null> | null } | null } | null> | null } };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, heroImage?: string | null, heroImageAlt?: string | null, primaryCtaLabel?: string | null, primaryCtaLink?: string | null, secondaryCtaLabel?: string | null, secondaryCtaLink?: string | null, capabilityEyebrow?: string | null, capabilityHeadline?: string | null, qualityEyebrow?: string | null, qualityHeadline?: string | null, qualityDescription?: string | null, proofEyebrow?: string | null, proofHeadline?: string | null, proofCtaLabel?: string | null, proofCtaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroStats?: Array<{ __typename: 'HomeHeroStats', value?: string | null, label?: string | null } | null> | null, capabilities?: Array<{ __typename: 'HomeCapabilities', title?: string | null, description?: string | null, spec?: string | null } | null> | null, qualityPoints?: Array<{ __typename: 'HomeQualityPoints', label?: string | null, value?: string | null } | null> | null, testimonials?: Array<{ __typename: 'HomeTestimonials', quote?: string | null, author?: string | null, role?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, heroImage?: string | null, heroImageAlt?: string | null, primaryCtaLabel?: string | null, primaryCtaLink?: string | null, secondaryCtaLabel?: string | null, secondaryCtaLink?: string | null, capabilityEyebrow?: string | null, capabilityHeadline?: string | null, qualityEyebrow?: string | null, qualityHeadline?: string | null, qualityDescription?: string | null, proofEyebrow?: string | null, proofHeadline?: string | null, proofCtaLabel?: string | null, proofCtaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, heroStats?: Array<{ __typename: 'HomeHeroStats', value?: string | null, label?: string | null } | null> | null, capabilities?: Array<{ __typename: 'HomeCapabilities', title?: string | null, description?: string | null, spec?: string | null } | null> | null, qualityPoints?: Array<{ __typename: 'HomeQualityPoints', label?: string | null, value?: string | null } | null> | null, testimonials?: Array<{ __typename: 'HomeTestimonials', quote?: string | null, author?: string | null, role?: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, timelineEyebrow?: string | null, timelineHeadline?: string | null, certificationsEyebrow?: string | null, certificationsHeadline?: string | null, footprintEyebrow?: string | null, footprintHeadline?: string | null, footprintDescription?: string | null, ctaLabel?: string | null, ctaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, milestones?: Array<{ __typename: 'AboutMilestones', year?: string | null, title?: string | null, description?: string | null } | null> | null, certifications?: Array<{ __typename: 'AboutCertifications', name?: string | null, details?: string | null } | null> | null, footprintStats?: Array<{ __typename: 'AboutFootprintStats', value?: string | null, label?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, timelineEyebrow?: string | null, timelineHeadline?: string | null, certificationsEyebrow?: string | null, certificationsHeadline?: string | null, footprintEyebrow?: string | null, footprintHeadline?: string | null, footprintDescription?: string | null, ctaLabel?: string | null, ctaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, milestones?: Array<{ __typename: 'AboutMilestones', year?: string | null, title?: string | null, description?: string | null } | null> | null, certifications?: Array<{ __typename: 'AboutCertifications', name?: string | null, details?: string | null } | null> | null, footprintStats?: Array<{ __typename: 'AboutFootprintStats', value?: string | null, label?: string | null } | null> | null } | null } | null> | null } };

export type ServicesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesQuery = { __typename?: 'Query', services: { __typename: 'Services', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, processEyebrow?: string | null, processHeadline?: string | null, ctaHeading?: string | null, ctaDescription?: string | null, ctaLabel?: string | null, ctaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, serviceCards?: Array<{ __typename: 'ServicesServiceCards', name?: string | null, description?: string | null, tolerance?: string | null, materials?: string | null } | null> | null, processSteps?: Array<{ __typename: 'ServicesProcessSteps', step?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type ServicesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesFilter>;
}>;


export type ServicesConnectionQuery = { __typename?: 'Query', servicesConnection: { __typename?: 'ServicesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesConnectionEdges', cursor: string, node?: { __typename: 'Services', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, processEyebrow?: string | null, processHeadline?: string | null, ctaHeading?: string | null, ctaDescription?: string | null, ctaLabel?: string | null, ctaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, serviceCards?: Array<{ __typename: 'ServicesServiceCards', name?: string | null, description?: string | null, tolerance?: string | null, materials?: string | null } | null> | null, processSteps?: Array<{ __typename: 'ServicesProcessSteps', step?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, formHeading?: string | null, formDescription?: string | null, uploadHint?: string | null, emailLabel?: string | null, emailValue?: string | null, phoneLabel?: string | null, phoneValue?: string | null, addressLabel?: string | null, addressValue?: string | null, hoursLabel?: string | null, hoursValue?: string | null, responseLabel?: string | null, responseValue?: string | null, testimonialQuote?: string | null, testimonialAuthor?: string | null, ctaLabel?: string | null, ctaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, title: string, heroEyebrow?: string | null, heroHeadline: string, heroDescription?: string | null, formHeading?: string | null, formDescription?: string | null, uploadHint?: string | null, emailLabel?: string | null, emailValue?: string | null, phoneLabel?: string | null, phoneValue?: string | null, addressLabel?: string | null, addressValue?: string | null, hoursLabel?: string | null, hoursValue?: string | null, responseLabel?: string | null, responseValue?: string | null, testimonialQuote?: string | null, testimonialAuthor?: string | null, ctaLabel?: string | null, ctaLink?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  siteName
  siteTagline
  logoText
  logoImage
  navLinks {
    __typename
    label
    href
  }
  navCtaLabel
  navCtaLink
  footerTagline
  footerLinks {
    __typename
    label
    href
  }
  copyrightText
  googleFontsUrl
  socialLinks {
    __typename
    platform
    url
  }
}
    `;
export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  heroImage
  heroImageAlt
  primaryCtaLabel
  primaryCtaLink
  secondaryCtaLabel
  secondaryCtaLink
  heroStats {
    __typename
    value
    label
  }
  capabilityEyebrow
  capabilityHeadline
  capabilities {
    __typename
    title
    description
    spec
  }
  qualityEyebrow
  qualityHeadline
  qualityDescription
  qualityPoints {
    __typename
    label
    value
  }
  proofEyebrow
  proofHeadline
  testimonials {
    __typename
    quote
    author
    role
  }
  proofCtaLabel
  proofCtaLink
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  timelineEyebrow
  timelineHeadline
  milestones {
    __typename
    year
    title
    description
  }
  certificationsEyebrow
  certificationsHeadline
  certifications {
    __typename
    name
    details
  }
  footprintEyebrow
  footprintHeadline
  footprintDescription
  footprintStats {
    __typename
    value
    label
  }
  ctaLabel
  ctaLink
}
    `;
export const ServicesPartsFragmentDoc = gql`
    fragment ServicesParts on Services {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  serviceCards {
    __typename
    name
    description
    tolerance
    materials
  }
  processEyebrow
  processHeadline
  processSteps {
    __typename
    step
    title
    description
  }
  ctaHeading
  ctaDescription
  ctaLabel
  ctaLink
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  title
  heroEyebrow
  heroHeadline
  heroDescription
  formHeading
  formDescription
  uploadHint
  emailLabel
  emailValue
  phoneLabel
  phoneValue
  addressLabel
  addressValue
  hoursLabel
  hoursValue
  responseLabel
  responseValue
  testimonialQuote
  testimonialAuthor
  ctaLabel
  ctaLink
}
    `;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ServicesDocument = gql`
    query services($relativePath: String!) {
  services(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesParts
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ServicesConnectionDocument = gql`
    query servicesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesFilter) {
  servicesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesParts
      }
    }
  }
}
    ${ServicesPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    services(variables: ServicesQueryVariables, options?: C): Promise<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}> {
        return requester<{data: ServicesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesQueryVariables, query: string}, ServicesQueryVariables>(ServicesDocument, variables, options);
      },
    servicesConnection(variables?: ServicesConnectionQueryVariables, options?: C): Promise<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesConnectionQueryVariables, query: string}, ServicesConnectionQueryVariables>(ServicesConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/dcf16d36-5bf7-453a-a56c-0f51f4d2192b/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  